{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irdb",
    "module": "irkit-library",
    "version": "2026.1.040620261650",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-library-2026.1.040620261650.aar",
          "url": "irkit-library-2026.1.040620261650.aar",
          "size": 6451563,
          "sha512": "03772e5a566c688d0d74b4c26480c703129608756cdf55ba419f1e000b5150d41937e6e0633d8fc0e3d2fbf564a0e2983d1f8cc6e7c1f532acb1fe9dc3e4daf2",
          "sha256": "2247afa85d0c442ff3f9c7f7b4155d4a6c3ebaa043d5dedd83909a5353774423",
          "sha1": "d44abcdfa7745dfd1d9d9d81b3fd1eee8c5f1706",
          "md5": "425664203b2c7f34c7dd65ff1b7a0124"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-video",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-svg",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.microsoft.onnxruntime",
          "module": "onnxruntime-android",
          "version": {
            "requires": "1.24.2"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-android",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "com.irdb",
          "module": "irkit-analytics",
          "version": {
            "requires": "2026.1.040620261650"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-library-2026.1.040620261650.aar",
          "url": "irkit-library-2026.1.040620261650.aar",
          "size": 6451563,
          "sha512": "03772e5a566c688d0d74b4c26480c703129608756cdf55ba419f1e000b5150d41937e6e0633d8fc0e3d2fbf564a0e2983d1f8cc6e7c1f532acb1fe9dc3e4daf2",
          "sha256": "2247afa85d0c442ff3f9c7f7b4155d4a6c3ebaa043d5dedd83909a5353774423",
          "sha1": "d44abcdfa7745dfd1d9d9d81b3fd1eee8c5f1706",
          "md5": "425664203b2c7f34c7dd65ff1b7a0124"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "irkit-library-2026.1.040620261650-sources.jar",
          "url": "irkit-library-2026.1.040620261650-sources.jar",
          "size": 155907,
          "sha512": "a5222b42feb968fded57ed67498bf8be6bc911bf746777b4f2542d91d66e5c7f15c6b20543954bdd8e8b0839cb9ad0a9ec5e33aa2a559dbcc9a684a0a0f0dc92",
          "sha256": "a89d610bdf217faa10ac6666e1b6f19ccb2094457282588a59fefc933799bd41",
          "sha1": "67445222f79f5870924ac0e9c8cd446f12b24aae",
          "md5": "e1b18aaf94746cc0c0f67b488e60e4c8"
        }
      ]
    }
  ]
}
