{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irdb",
    "module": "irkit-analytics",
    "version": "2026.1.022020261207",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-analytics-2026.1.022020261207.aar",
          "url": "irkit-analytics-2026.1.022020261207.aar",
          "size": 307319,
          "sha512": "0f72d884c3891dca755a57e470ec844931abdfbf3082499b2f11f4afd2c26f17441fd391e6423e8d28de1b38188b529f915c9568c8acc0dc35dff81f161aeb9c",
          "sha256": "4ad6cf33693fc5163eb88a9d1ee67a54513894a41e825b88b9df0d24e2d91638",
          "sha1": "47b81d96698ff9f72accabf3c98e907a170153b2",
          "md5": "e51b8e1a106dac3fb666e5fb66e1d0b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-analytics-2026.1.022020261207.aar",
          "url": "irkit-analytics-2026.1.022020261207.aar",
          "size": 307319,
          "sha512": "0f72d884c3891dca755a57e470ec844931abdfbf3082499b2f11f4afd2c26f17441fd391e6423e8d28de1b38188b529f915c9568c8acc0dc35dff81f161aeb9c",
          "sha256": "4ad6cf33693fc5163eb88a9d1ee67a54513894a41e825b88b9df0d24e2d91638",
          "sha1": "47b81d96698ff9f72accabf3c98e907a170153b2",
          "md5": "e51b8e1a106dac3fb666e5fb66e1d0b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "irkit-analytics-2026.1.022020261207-sources.jar",
          "url": "irkit-analytics-2026.1.022020261207-sources.jar",
          "size": 57079,
          "sha512": "4539e699564a53b63eec7a096423ac83fd602cd4e407187434238d3a8f4d9303a11f00fcb90e2a5d94d0826c5bfeacedec6fde86fec028dd66317e49bd3a4e21",
          "sha256": "a230a1665dbc506a486c7bb1d48844831f220763aa9a093b9d88df296f6f9b02",
          "sha1": "2911f327b46c6af18f183f0ab4e538187f667b82",
          "md5": "287b5548bc8e7e69ac9a7e776feeca31"
        }
      ]
    }
  ]
}
