{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irdb",
    "module": "irkit-ui",
    "version": "2026.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-ui-2026.1.aar",
          "url": "irkit-ui-2026.1.aar",
          "size": 740298,
          "sha512": "dd123bd41ff7605e3b9a90eb9834fb03f8758fe0b31c29814b2698134d587bdf7d57be8444c7f4115a53248621efcf0034e31d9334f7e1f0acc3f70dfcc3e6ad",
          "sha256": "64d7a2b47bcc1b5c8551f72c3704f83a3a8d48e513ee8dae6e7cd6093bebf74d",
          "sha1": "b19f2fb2d93ffe72dde06a9ffe83ab1601b6eb5c",
          "md5": "b128640e8cc02446a5e0a6170a5af093"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.irdb",
          "module": "irkit-core",
          "version": {
            "requires": "2026.1"
          }
        },
        {
          "group": "com.irdb",
          "module": "irkit-analytics",
          "version": {
            "requires": "2026.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-video",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-svg",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-ui-2026.1.aar",
          "url": "irkit-ui-2026.1.aar",
          "size": 740298,
          "sha512": "dd123bd41ff7605e3b9a90eb9834fb03f8758fe0b31c29814b2698134d587bdf7d57be8444c7f4115a53248621efcf0034e31d9334f7e1f0acc3f70dfcc3e6ad",
          "sha256": "64d7a2b47bcc1b5c8551f72c3704f83a3a8d48e513ee8dae6e7cd6093bebf74d",
          "sha1": "b19f2fb2d93ffe72dde06a9ffe83ab1601b6eb5c",
          "md5": "b128640e8cc02446a5e0a6170a5af093"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "irkit-ui-2026.1-sources.jar",
          "url": "irkit-ui-2026.1-sources.jar",
          "size": 101796,
          "sha512": "b33c94f99595ab21c848535ecf795d96bf4ee8bf65cd753b6d7a3d84b3aa5fbb54b33293be1598e2c2d8f6f02a1455532f54de9674c7e63ec16c06831c06fd67",
          "sha256": "90b983075c6c5dc35910a8c444e343f5ab4fc7a2a143a90d5b557c6b2c191fec",
          "sha1": "22f54f3d07d894ec21037fc5fdef47cabeba76bb",
          "md5": "917289c5facb8e92ea776c099945fdce"
        }
      ]
    }
  ]
}
