{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irdb",
    "module": "irkit-ui",
    "version": "2026.1.043020261341",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-ui-2026.1.043020261341.aar",
          "url": "irkit-ui-2026.1.043020261341.aar",
          "size": 1014887,
          "sha512": "c966938ee328f350aefeaf43bf215a70e3605ef22fa2bb7a4fd8adaabeb7d8540f19cd4f519877e820e45d61c7a7ebd078de63a799466872c670425c5a4c6258",
          "sha256": "af3ec4dc082d7f8c8761c8221d2e10aaa6bea7c9cbf5092ef128f3200a4e3a5c",
          "sha1": "f86c1672b090cca5f76909c3e95e9afd9070ed90",
          "md5": "d04cb17c97d86c19f100a007d8959161"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.irdb",
          "module": "irkit-library",
          "version": {
            "requires": "2026.1.043020261341"
          }
        },
        {
          "group": "com.irdb",
          "module": "irkit-analytics",
          "version": {
            "requires": "2026.1.043020261341"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-video",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-svg",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-ui-2026.1.043020261341.aar",
          "url": "irkit-ui-2026.1.043020261341.aar",
          "size": 1014887,
          "sha512": "c966938ee328f350aefeaf43bf215a70e3605ef22fa2bb7a4fd8adaabeb7d8540f19cd4f519877e820e45d61c7a7ebd078de63a799466872c670425c5a4c6258",
          "sha256": "af3ec4dc082d7f8c8761c8221d2e10aaa6bea7c9cbf5092ef128f3200a4e3a5c",
          "sha1": "f86c1672b090cca5f76909c3e95e9afd9070ed90",
          "md5": "d04cb17c97d86c19f100a007d8959161"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "irkit-ui-2026.1.043020261341-sources.jar",
          "url": "irkit-ui-2026.1.043020261341-sources.jar",
          "size": 118113,
          "sha512": "5d7d4c5533f992dcb8387b289ee76896a630be8ec1b637afbc595933f87bc3a2bd624e9d6671d49abd7edcb796f6757ec243a1027931fea729e6fcc60ea326c8",
          "sha256": "f2104300941c42c25877154a9ee8a88bc2505bfcc65412efecef10f1dfafc24d",
          "sha1": "0c9f346be8eca84443f97262cda81200c2ed1781",
          "md5": "d95672c98ed14db767166ac60c4c9b7f"
        }
      ]
    }
  ]
}
