{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irdb",
    "module": "irkit-ui",
    "version": "2026.1.03302026",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-ui-2026.1.03302026.aar",
          "url": "irkit-ui-2026.1.03302026.aar",
          "size": 978664,
          "sha512": "ddfd2d5096e970afa0e1d2f7fe11f773317784b581876dd20757f7a2d755bd48586d7e14de3d1c552a99933cd7b1d53832397476e5a14d5b3400029d57ffdb83",
          "sha256": "c47ba7b780d6ff76ff2d3450ebd63c5271cad0ddb1677b83a1c0fb89bcf8e6cf",
          "sha1": "21f1301e8b53f29b163d00bc67ec428673d99978",
          "md5": "b851b3d43ff835fb843996661238fdba"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.irdb",
          "module": "irkit-library",
          "version": {
            "requires": "2026.1.03302026"
          }
        },
        {
          "group": "com.irdb",
          "module": "irkit-analytics",
          "version": {
            "requires": "2026.1.03302026"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-video",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-svg",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-ui-2026.1.03302026.aar",
          "url": "irkit-ui-2026.1.03302026.aar",
          "size": 978664,
          "sha512": "ddfd2d5096e970afa0e1d2f7fe11f773317784b581876dd20757f7a2d755bd48586d7e14de3d1c552a99933cd7b1d53832397476e5a14d5b3400029d57ffdb83",
          "sha256": "c47ba7b780d6ff76ff2d3450ebd63c5271cad0ddb1677b83a1c0fb89bcf8e6cf",
          "sha1": "21f1301e8b53f29b163d00bc67ec428673d99978",
          "md5": "b851b3d43ff835fb843996661238fdba"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "irkit-ui-2026.1.03302026-sources.jar",
          "url": "irkit-ui-2026.1.03302026-sources.jar",
          "size": 110333,
          "sha512": "8d3b4b9aeacf512c3f9c4a829e076e202a769ad6b24d7a028694a25f8bdeb63e35b3795d0ceb10e0f5c3faf2883ea21c455acb66ce71705b619596b4d8248254",
          "sha256": "ef83806dd8c396faad179075e28988a52c37fa285417a2c017b816b3db72a536",
          "sha1": "1ad016d3402a40691e45a6ada4d86077a207748e",
          "md5": "9eda2845dde14fc9795ece011d04d7aa"
        }
      ]
    }
  ]
}
