{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irdb",
    "module": "irkit-ui",
    "version": "2026.1.040620261650",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-ui-2026.1.040620261650.aar",
          "url": "irkit-ui-2026.1.040620261650.aar",
          "size": 1002137,
          "sha512": "76e9689ecaf1940e1b55a6cc92925fb16554407470ba6a3370e1b0d834388161dc480d663241a92bf9952d3e94377c300b9186825ad8ae5e1ea3307df4ee405f",
          "sha256": "9d84ec62b64a72c841aa69b4979a0c552d1cd2978d218579c8c1b7d0dd2218dc",
          "sha1": "8298dacacdfed779b5c4497d4bd9ea884dfdd4bb",
          "md5": "fc95a86717e163e386e31f6bf1061abd"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.irdb",
          "module": "irkit-library",
          "version": {
            "requires": "2026.1.040620261650"
          }
        },
        {
          "group": "com.irdb",
          "module": "irkit-analytics",
          "version": {
            "requires": "2026.1.040620261650"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-video",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-svg",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-ui-2026.1.040620261650.aar",
          "url": "irkit-ui-2026.1.040620261650.aar",
          "size": 1002137,
          "sha512": "76e9689ecaf1940e1b55a6cc92925fb16554407470ba6a3370e1b0d834388161dc480d663241a92bf9952d3e94377c300b9186825ad8ae5e1ea3307df4ee405f",
          "sha256": "9d84ec62b64a72c841aa69b4979a0c552d1cd2978d218579c8c1b7d0dd2218dc",
          "sha1": "8298dacacdfed779b5c4497d4bd9ea884dfdd4bb",
          "md5": "fc95a86717e163e386e31f6bf1061abd"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "irkit-ui-2026.1.040620261650-sources.jar",
          "url": "irkit-ui-2026.1.040620261650-sources.jar",
          "size": 112499,
          "sha512": "447c540af4eaa7cdeffd8b4edc255fc292829add5456fd8722212bb546923cf12b5c196275d4d46fc98e162a7e698f319a9b079c42f35a6797e2219d874fcde4",
          "sha256": "3b35318d78c2d4e4faafab8f2fce53ba7340ebd6689b36098a47b3fe2ad3b8f1",
          "sha1": "baaa09480ec65a07fdfc1de417b239ada8018b0b",
          "md5": "f360ae9c9616bb72ba38cae259e332ff"
        }
      ]
    }
  ]
}
