{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irdb",
    "module": "irkit-ui",
    "version": "25.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-ui-25.7.aar",
          "url": "irkit-ui-25.7.aar",
          "size": 623939,
          "sha512": "c6aaa8c8631ca8638045401f6dcfd3dac59d0e13a82bfc997b9f81e812fce61ca407a28e0d590a00c3ec40a371f31e02946f4baccdacdb2d60bb858ea1be1354",
          "sha256": "73e84ef919815b6909acc61ffa795bea8d916ccb488f21e8183a1b47d6a77f65",
          "sha1": "dbdb68b9c2d62fc11bb141ef3b6a4df101af9fd9",
          "md5": "faa4e62621b3fa80e61ddc09f552c13b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.irdb",
          "module": "irkit-library",
          "version": {
            "requires": "25.7"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-video",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-svg",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-ui-25.7.aar",
          "url": "irkit-ui-25.7.aar",
          "size": 623939,
          "sha512": "c6aaa8c8631ca8638045401f6dcfd3dac59d0e13a82bfc997b9f81e812fce61ca407a28e0d590a00c3ec40a371f31e02946f4baccdacdb2d60bb858ea1be1354",
          "sha256": "73e84ef919815b6909acc61ffa795bea8d916ccb488f21e8183a1b47d6a77f65",
          "sha1": "dbdb68b9c2d62fc11bb141ef3b6a4df101af9fd9",
          "md5": "faa4e62621b3fa80e61ddc09f552c13b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "irkit-ui-25.7-sources.jar",
          "url": "irkit-ui-25.7-sources.jar",
          "size": 173766,
          "sha512": "281a0f677b361f801d3b6489b00f05cadef4c12408c7900205a8f9f5b4d195b6cf57837e42a7a610ebd9bcf088da5ed4b00566cdee7948d242cc3f2436399365",
          "sha256": "e16b3bc83516d608d902856cf177c547acd76734e17ed501dd0d9f6615dabcb1",
          "sha1": "340e9683ca0c4f8ef4a0459bd5708c0701ac86aa",
          "md5": "1218027ebb253d904f086f9c855ff93d"
        }
      ]
    }
  ]
}
